spring:
  datasource:
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: never

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    #defer-datasource-initialization: true
    #generate-ddl: true

  sql:
    init:
      mode: always
      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/data.sql

server:
  port: 8080

loging.level:
    org.hibernate.SQL: debug
